In [1]:
import pandas as pd
import seaborn as sns

The next cell loads the `diamonds` dataset from Seaborn

In [2]:
data = sns.load_dataset('diamonds')

Display the first 5 rows of `data`

In [3]:
data.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

Sort `data` by ALL of the columns `cut`, `clarity`, and `color` columns. Then create a MultiIndex by setting the index of `data` to ALL `cut`, `clarity`, and `color`. Display the first 5 rows of `data`.

In [4]:
data = data.sort_values(["cut","clarity", "color"])
data = data.set_index(["cut", "clarity", "color"])
data.head()

                     carat  depth  table  price     x     y     z
cut   clarity color
Ideal IF      D       0.51   62.0   56.0   3446  5.14  5.18  3.20
              D       0.51   62.1   55.0   3446  5.12  5.13  3.19
              D       0.53   61.5   54.0   3517  5.27  5.21  3.22
              D       0.53   62.2   55.0   3812  5.17  5.19  3.22
              D       0.63   61.2   53.0   3832  5.55  5.60  3.41

Group `data` by `cut` and `clarity` using the `mean` function, and save the result as a variable `grouped`. Display `grouped`.

In [5]:
data.reset_index()
grouped = data.groupby(["cut","clarity"]).mean()
grouped

                      carat      depth      table        price         x  \
cut       clarity
Ideal     IF       0.455041  61.645710  55.707013  2272.913366  4.827261
          VVS1     0.495960  61.679091  55.839912  2468.129458  4.960596
          VVS2     0.586213  61.690714  55.915848  3250.290100  5.214693
          VS1      0.674714  61.706436  55.894037  3489.744497  5.449746
          VS2      0.670566  61.730901  55.931256  3284.550385  5.428111
          SI1      0.801808  61.737482  56.061023  3752.118169  5.781287
          SI2      1.007925  61.701001  56.120516  4755.952656  6.262621
          I1       1.222671  61.648630  56.102740  4335.726027  6.751712
Premium   IF       0.603478  61.047826  58.730435  3856.143478  5.234957
          VVS1     0.534821  61.260877  58.674513  2831.206169  5.037955
          VVS2     0.654724  61.280230  58.654483  3795.122989  5.390920
          VS1      0.793308  61.318451  58.690397  4485.462041  5.738049
          VS2      0.833774  61.283408  58.754155  4550.331248  5.834665
          SI1      0.908601  61.303329  58.758993  4455.269371  6.045410
          SI2      1.144161  61.178976  58.779654  5545.936928  6.569495
          I1       1.287024  61.183415  59.068293  3947.331707  6.842098
Very Good IF       0.618769  61.363806  57.455224  4396.216418  5.293097
          VVS1     0.494588  61.675919  57.622687  2459.441065  4.895513
          VVS2     0.566389  61.660972  57.712308  3037.765182  5.083004
          VS1      0.733307  61.729127  57.822197  3805.353239  5.575758
          VS2      0.811181  61.849247  57.958665  4215.759552  5.769097
          SI1      0.845978  61.947222  58.014907  3932.391049  5.869244
          SI2      1.064338  61.862952  58.251571  4988.688095  6.365814
          I1       1.281905  61.755952  59.372619  4078.226190  6.800119
Good      IF       0.616338  61.440845  59.056338  4098.323944  5.278310
          VVS1     0.502312  62.123118  58.922581  2254.774194  4.926290
          VVS2     0.614930  62.311538  58.672727  3079.108392  5.246154
          VS1      0.757685  62.018673  58.775772  3801.445988  5.636852
          VS2      0.850787  62.363292  58.664826  4262.236196  5.863262
          SI1      0.830397  62.696346  58.430962  3689.533333  5.799776
          SI2      1.035227  62.242831  58.924977  4580.260870  6.272414
          I1       1.203021  62.067708  59.497917  3596.635417  6.651562
Fair      IF       0.474444  60.066667  59.111111  1912.333333  5.050000
          VVS1     0.664706  60.417647  61.235294  3871.352941  5.503529
          VVS2     0.691594  62.847826  59.237681  3349.768116  5.495507
          VS1      0.879824  62.945294  60.365294  4165.141176  5.932353
          VS2      0.885249  63.637548  59.050958  4174.724138  5.966590
          SI1      0.964632  63.910294  59.126961  4208.279412  6.127230
          SI2      1.203841  64.421888  58.828326  5173.916309  6.570343
          I1       1.361000  65.699048  58.114286  3703.533333  6.723000

                          y         z
cut       clarity
Ideal     IF       4.850289  2.982211
          VVS1     4.978012  3.064304
          VVS2     5.231869  3.221550
          VS1      5.470635  3.366615
          VS2      5.434484  3.352102
          SI1      5.791226  3.570801
          SI2      6.268853  3.865889
          I1       6.736712  4.158493
Premium   IF       5.220870  3.191478
          VVS1     5.018847  3.080000
          VVS2     5.367126  3.295920
          VS1      5.710935  3.509703
          VS2      5.806175  3.565639
          SI1      6.009731  3.692162
          SI2      6.543822  4.001967
          I1       6.785902  4.130683
Very Good IF       5.334403  3.259813
          VVS1     4.927503  3.031420
          VVS2     5.115911  3.144348
          VS1      5.607448  3.467177
          VS2      5.799263  3.576144
          SI1      5.897009  3.643451
          SI2      6.391233  3.944495
          I1       6.796071  4.197381
Good      IF       5.315070  3.252958
          VVS1     4.950806  3.068602
          VVS2     5.269406  3.273497
          VS1      5.657176  3.499954
          VS2      5.878395  3.658231
          SI1      5.809974  3.635064
          SI2      6.276577  3.895245
          I1       6.614792  4.065625
Fair      IF       5.050000  3.033333
          VVS1     5.508824  3.327647
          VVS2     5.464638  3.444058
          VS1      5.864059  3.709882
          VS2      5.907011  3.780230
          SI1      6.071985  3.895711
          SI2      6.503927  4.211867
          I1       6.624238  4.386905

Display a cross-section of `grouped` using the `VVS1` clarity.

In [6]:
grouped.xs("VVS1", level = "clarity").head()

,carat,depth,table,price,x,y,z
cut,,,,,,,
Ideal,0.495960,61.679091,55.839912,2468.129458,4.960596,4.978012,3.064304
Premium,0.534821,61.260877,58.674513,2831.206169,5.037955,5.018847,3.080000
Very Good,0.494588,61.675919,57.622687,2459.441065,4.895513,4.927503,3.031420
Good,0.502312,62.123118,58.922581,2254.774194,4.926290,4.950806,3.068602
Fair,0.664706,60.417647,61.235294,3871.352941,5.503529,5.508824,3.327647